[package]
name = "hopalong_map"
version = "0.1.1"
authors = ["Víctor Baena <victormage@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
fltk = { version = "0.3.10"}
